/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lydiagetachew;

import org.junit.Test;
import static org.junit.Assert.*;

public class LabTest {
    @Test
    public void testSomeLibraryMethod() {

    }
}
